In [1]:
import numpy as np

In [2]:
A = np.array([[-1, -7],
              [-1, -7]], dtype=float)

print("Matrix A:\n", A)

Matrix A:
 [[-1. -7.]
 [-1. -7.]]


In [3]:
AT = A.T
ATA = AT @ A

print("\nA^T A:\n", ATA)


A^T A:
 [[ 2. 14.]
 [14. 98.]]


In [4]:
eigenvalues, V = np.linalg.eig(ATA)

print("\nEigenvalues of A^T A:\n", eigenvalues)
print("\nEigenvectors (V):\n", V)


Eigenvalues of A^T A:
 [  0. 100.]

Eigenvectors (V):
 [[-0.98994949 -0.14142136]
 [ 0.14142136 -0.98994949]]


In [5]:
singular_values = np.sqrt(np.abs(eigenvalues))
print("\nSingular values:\n", singular_values)


Singular values:
 [ 0. 10.]


In [6]:
idx = np.argsort(-singular_values)
singular_values = singular_values[idx]
V = V[:, idx]

print("\nSorted Singular values:\n", singular_values)
print("\nSorted V matrix:\n", V)


Sorted Singular values:
 [10.  0.]

Sorted V matrix:
 [[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]


In [7]:
Sigma = np.zeros((2,2))
Sigma[0,0] = singular_values[0]
Sigma[1,1] = singular_values[1]

print("\nSigma matrix:\n", Sigma)


Sigma matrix:
 [[10.  0.]
 [ 0.  0.]]


In [8]:
U = np.zeros((2,2))

for i in range(2):
    if singular_values[i] != 0:
        U[:,i] = (A @ V[:,i]) / singular_values[i]
    else:
        # orthogonal vector (Gram-Schmidt for zero σ)
        U[:,i] = np.array([-U[1,0], U[0,0]])

print("\nU matrix:\n", U)


U matrix:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [9]:
VT = V.T
print("\nV^T matrix:\n", VT)


V^T matrix:
 [[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]


In [10]:
A_reconstructed = U @ Sigma @ VT

print("\nReconstructed A:\n", A_reconstructed)

print("\nError (A - reconstructed):\n", A - A_reconstructed)


Reconstructed A:
 [[-1. -7.]
 [-1. -7.]]

Error (A - reconstructed):
 [[-1.11022302e-16 -8.88178420e-16]
 [-1.11022302e-16 -8.88178420e-16]]
